import { lazy, Suspense, useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, type ContentCommand, type Platform } from '../../shared/api/client'
import { useAccess } from '../../shared/access/AccessProvider'
import { useI18n } from '../../shared/i18n/I18nProvider'
import { Field, PageHeader, Panel, StatusBadge, Tabs } from '../../shared/ui/Primitives'
import styles from './PublishingPage.module.scss'
import { draftPayload, emptyComposerOptions, isFutureMoscowSchedule, moscowScheduleToISO, type ComposerAccount, type ComposerOptions, type TikTokCapability } from './composer'
import { publishingErrorMessage, publishingQueryKey, useContentCommands, useContentItem, useMediaUpload } from './hooks/publishing'

const VideoEditor = lazy(() => import('./VideoEditor'))
const PlanningBoard = lazy(() => import('./PlanningBoard'))
const label: Record<Platform, string> = { TIKTOK: 'TikTok', INSTAGRAM: 'Instagram', YOUTUBE: 'YouTube Shorts', VK: 'VK Video' }
const actionLabel: Record<string, string> = { submit: 'Отправить на согласование', publish: 'Опубликовать', schedule: 'Запланировать', cancel: 'Отменить публикацию' }

export function PublishingPage() {
  const { t, locale } = useI18n(); const access = useAccess(); const client = useQueryClient(); const own = access.role === 'CREATOR'
  const [tab, setTab] = useState<'PLAN' | 'COMPOSE'>('PLAN'); const [creatorID, setCreatorID] = useState(own ? access.principal?.activeContext.creatorId ?? '' : '')
  const [description, setDescription] = useState(''); const [hashtags, setHashtags] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [file, setFile] = useState<File | null>(null); const [alternateFiles, setAlternateFiles] = useState<Record<string, File>>({}); const [alternateMedia, setAlternateMedia] = useState<Record<string, string>>({})
  const [schedule, setSchedule] = useState(''); const [message, setMessage] = useState(''); const [savedID, setSavedID] = useState(''); const [showEditor, setShowEditor] = useState(false); const [options, setOptions] = useState<ComposerOptions>(emptyComposerOptions)
  const dirty = Boolean(file || Object.keys(alternateFiles).length || description || hashtags || selected.length || schedule || options.youtubeTitle || options.vkTitle)
  const detail = useContentItem(savedID, own); const commands = useContentCommands(own); const { upload } = useMediaUpload(own)
  const creators = useQuery({ queryKey: ['publishing-creators', access.scopeKey, locale], queryFn: api.creators, enabled: !own })
  const managed = useQuery({ queryKey: ['publishing-accounts', access.scopeKey, locale, creatorID], queryFn: () => api.creatorAccounts(creatorID), enabled: !own && Boolean(creatorID) })
  const mine = useQuery({ queryKey: ['publishing-own-accounts', access.scopeKey, locale], queryFn: api.ownSocials, enabled: own })
  const accounts = useMemo<ComposerAccount[]>(() => own ? (mine.data?.items ?? []).map(x => ({ id: x.id, platform: x.platform, displayName: x.displayName, username: x.username, status: x.status })) : (managed.data?.items ?? []).map(x => ({ id: x.id, platform: x.platform as Platform, displayName: x.displayName, username: x.username, status: x.status })), [managed.data, mine.data, own])
  const selectedAccounts = accounts.filter(x => selected.includes(x.id)); const tiktokSelected = selectedAccounts.filter(x => x.platform === 'TIKTOK')
  const readiness = useQuery({ queryKey: publishingQueryKey('composer-preflight', access.scopeKey, locale, own, creatorID, selected.join(',')), queryFn: () => api.composerPreflight({ creatorId: own ? undefined : creatorID, accountIds: selected }), enabled: Boolean(selected.length && (own || creatorID)), retry: false })
  const tiktokCapability = useMemo<TikTokCapability | undefined>(() => readiness.data?.targets.find(x => x.platform === 'TIKTOK')?.preflight.tiktok, [readiness.data])
  const previewURL = useMemo(() => file ? URL.createObjectURL(file) : '', [file]); useEffect(() => () => { if (previewURL) URL.revokeObjectURL(previewURL) }, [previewURL])
  useEffect(() => { const onUnload = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = '' } }; window.addEventListener('beforeunload', onUnload); return () => window.removeEventListener('beforeunload', onUnload) }, [dirty])
  const setOption = <K extends keyof ComposerOptions>(key: K, value: ComposerOptions[K]) => setOptions(current => ({ ...current, [key]: value }))
  const reset = () => { setDescription(''); setHashtags(''); setSelected([]); setFile(null); setAlternateFiles({}); setAlternateMedia({}); setSchedule(''); setSavedID(''); setOptions(emptyComposerOptions()) }
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id])
  const setAlternate = (id: string, next: File | null) => setAlternateFiles(current => { const copy = { ...current }; if (next) copy[id] = next; else delete copy[id]; return copy })
  const save = useMutation({ mutationFn: async () => {
    if (!file) throw new Error(t('Выберите вертикальное видео.')); if (!own && !creatorID) throw new Error(t('Выберите креатора.')); if (!selected.length) throw new Error(t('Выберите хотя бы один аккаунт.')); if (schedule && !isFutureMoscowSchedule(schedule)) throw new Error(t('Выберите будущее время по Москве.'))
    if (readiness.isPending) throw new Error(t('Проверяем совместимость площадок.')); if (readiness.data?.targets.some(target => !target.preflight.compatible)) throw new Error(t('Исправьте несовместимые настройки площадок.'))
    if (tiktokSelected.length && (!options.tiktokPrivacy || options.comments === null || options.duet === null || options.stitch === null || !options.explicitConsent || !options.musicUsageConfirmed)) throw new Error(t('Заполните обязательные настройки TikTok.'))
    const base = await upload(file, creatorID); const alternate: Record<string, string> = {}; for (const account of selectedAccounts) if (alternateFiles[account.id]) alternate[account.id] = (await upload(alternateFiles[account.id], creatorID)).mediaAssetId
    setAlternateMedia(alternate); const payload = draftPayload(creatorID, own, description, hashtags, accounts, selected, base.mediaAssetId, options, alternate)
    return own ? api.createOwnContentItem(payload, crypto.randomUUID()) : api.createContentItem(payload, crypto.randomUUID())
  }, onSuccess: async draft => { setSavedID(draft.id); setMessage(t('Черновик сохранён.')); await Promise.all([client.invalidateQueries({ queryKey: ['publishing', 'items'] }), client.fetchQuery({ queryKey: publishingQueryKey('detail', access.scopeKey, locale, own, draft.id), queryFn: () => own ? api.ownContentItem(draft.id) : api.contentItem(draft.id) })]) }, onError: error => setMessage(publishingErrorMessage(error, t)) })
  const command = (action: ContentCommand) => { if (!detail.data?.availableActions.includes(action)) return; if (action === 'schedule' && !isFutureMoscowSchedule(schedule)) { setMessage(t('Выберите будущее время по Москве.')); return }; commands.mutate({ id: detail.data.id, action, scheduledAt: action === 'schedule' ? moscowScheduleToISO(schedule) : undefined }, { onSuccess: () => setMessage(t('Действие выполнено.')), onError: error => setMessage(publishingErrorMessage(error, t)) }) }
  const leave = () => { if (!dirty || window.confirm(t('Есть несохранённые изменения. Закрыть черновик?'))) { reset(); setTab('PLAN') } }
  return <section className={styles.page}>
    <PageHeader eyebrow={t('КОНТЕНТ')} title={t('Планирование публикаций')} description={t('Одно вертикальное видео — несколько площадок, отдельный результат для каждого аккаунта.')} actions={<button className={styles.primary} onClick={() => setTab('COMPOSE')}>{t('Новая публикация')}</button>} />
    <Tabs label={t('Раздел публикаций')} value={tab} onChange={value => value === 'PLAN' ? leave() : setTab('COMPOSE')} items={[{ value: 'PLAN', label: t('Планирование') }, { value: 'COMPOSE', label: t('Новый черновик') }]} />
    {message ? <div className={styles.notice} role="status">{message}</div> : null}
    {tab === 'PLAN' ? <Suspense fallback={<Panel>{t('Загрузка…')}</Panel>}><PlanningBoard own={own} /></Suspense> : <div className={styles.composer}>
      <Panel className={styles.form}>
        {!own ? <Field label={t('Креатор')}><select value={creatorID} onChange={event => { setCreatorID(event.target.value); setSelected([]) }}><option value="">{t('Выберите креатора')}</option>{creators.data?.items.map(x => <option key={x.id} value={x.id}>{x.displayName}</option>)}</select></Field> : null}
        <Field label={t('Вертикальное видео')} hint={t('Файл загружается напрямую в приватное хранилище.')}><input aria-label={t('Вертикальное видео')} type="file" accept="video/*" onChange={event => { setFile(event.target.files?.[0] ?? null); setSavedID('') }} /></Field>
        <Field label={t('Общее описание')}><textarea rows={6} value={description} onChange={event => setDescription(event.target.value)} /></Field><Field label={t('Хештеги')}><input value={hashtags} onChange={event => setHashtags(event.target.value)} /></Field>
        <Field label={t('Опубликовать по московскому времени')} error={schedule && !isFutureMoscowSchedule(schedule) ? t('Выберите будущее время по Москве.') : undefined}><input type="datetime-local" value={schedule} onChange={event => setSchedule(event.target.value)} /></Field>
        <fieldset><legend>{t('Аккаунты площадок')}</legend>{accounts.map(account => <div className={styles.account} key={account.id}><label><input aria-label={`${label[account.platform]} ${account.username || account.displayName}`} type="checkbox" checked={selected.includes(account.id)} disabled={account.status !== 'ACTIVE'} onChange={() => toggle(account.id)} /><b>{label[account.platform]}</b><small>@{account.username || account.displayName}</small></label><StatusBadge tone={account.status === 'ACTIVE' ? 'success' : 'warning'}>{account.status}</StatusBadge>{selected.includes(account.id) ? <label>{t('Alternate media')}<input aria-label={`${label[account.platform]} alternate media`} type="file" accept="video/*" onChange={event => setAlternate(account.id, event.target.files?.[0] ?? null)} />{alternateMedia[account.id] ? <small>{t('Alternate media uploaded')}</small> : null}</label> : null}</div>)}</fieldset>
        {selectedAccounts.some(x => x.platform === 'YOUTUBE') ? <YouTubePanel options={options} setOption={setOption} t={t} /> : null}
        {selectedAccounts.some(x => x.platform === 'VK') ? <VKPanel options={options} setOption={setOption} t={t} /> : null}
        {tiktokSelected.length ? <TikTokPanel options={options} capability={tiktokCapability} setOption={setOption} t={t} /> : null}
        <Preflight result={readiness.data} pending={readiness.isPending} t={t} />
        <div className={styles.actions}><button type="button" onClick={leave}>{t('Отмена')}</button>{savedID ? (detail.data?.availableActions ?? []).filter(x => x in actionLabel).map(action => <button type="button" key={action} className={action === 'publish' ? styles.primary : ''} disabled={commands.isPending} onClick={() => command(action as ContentCommand)}>{t(actionLabel[action])}</button>) : <button className={styles.primary} type="button" disabled={save.isPending} onClick={() => save.mutate()}>{save.isPending ? t('Загрузка…') : t('Сохранить черновик')}</button>}</div>
      </Panel>
      <Panel className={styles.preview}><div className={styles.phone}>{previewURL ? <video src={previewURL} controls muted playsInline /> : <span>{t('Предпросмотр видео')}</span>}</div><h3>{options.youtubeTitle || description || t('Описание появится здесь')}</h3><p>{hashtags}</p><Field label={t('Cover frame')}><input type="time" step="1" value={options.coverFrame} onChange={event => setOption('coverFrame', event.target.value)} /><button type="button" onClick={() => setShowEditor(true)}>{t('Open frame editor')}</button></Field></Panel>
    </div>}
    {showEditor ? <Suspense fallback={<span>{t('Загрузка…')}</span>}><VideoEditor src={previewURL} value={options.coverFrame} onChange={value => setOption('coverFrame', value)} onClose={() => setShowEditor(false)} /></Suspense> : null}
  </section>
}
function YouTubePanel({ options, setOption, t }: { options: ComposerOptions; setOption: <K extends keyof ComposerOptions>(key: K, value: ComposerOptions[K]) => void; t: (key: string) => string }) { return <fieldset><legend>YouTube</legend><Field label={t('YouTube title')}><input value={options.youtubeTitle} onChange={e => setOption('youtubeTitle', e.target.value)} /></Field><Field label={t('YouTube category ID')}><input value={options.youtubeCategoryId} onChange={e => setOption('youtubeCategoryId', e.target.value)} /></Field><Field label={t('YouTube privacy')}><select value={options.youtubePrivacy} onChange={e => setOption('youtubePrivacy', e.target.value)}><option value="">{t('Choose privacy')}</option><option value="private">Private</option><option value="unlisted">Unlisted</option><option value="public">Public</option></select></Field><Choice label={t('Made for kids')} value={options.madeForKids} onChange={v => setOption('madeForKids', v)} /><Choice label={t('Notify subscribers')} value={options.notifySubscribers} onChange={v => setOption('notifySubscribers', v)} /></fieldset> }
function VKPanel({ options, setOption, t }: { options: ComposerOptions; setOption: <K extends keyof ComposerOptions>(key: K, value: ComposerOptions[K]) => void; t: (key: string) => string }) { return <fieldset><legend>VK Video</legend><Field label={t('VK owner')}><select value={options.vkOwner} onChange={e => setOption('vkOwner', e.target.value as ComposerOptions['vkOwner'])}><option value="">{t('Choose owner')}</option><option value="user">User</option><option value="community">Community</option></select></Field><Field label={t('VK owner ID')}><input value={options.vkOwnerId} onChange={e => setOption('vkOwnerId', e.target.value)} /></Field><Field label={t('VK title')}><input value={options.vkTitle} onChange={e => setOption('vkTitle', e.target.value)} /></Field><Field label={t('VK privacy')}><select value={options.vkPrivacy} onChange={e => setOption('vkPrivacy', e.target.value as ComposerOptions['vkPrivacy'])}><option value="">{t('Choose privacy')}</option><option value="public">Public</option><option value="private">Private</option></select></Field><label><input type="checkbox" checked={options.vkWallPost} onChange={e => setOption('vkWallPost', e.target.checked)} />{t('VK wall post')}</label></fieldset> }
function TikTokPanel({ options, capability, setOption, t }: { options: ComposerOptions; capability?: TikTokCapability; setOption: <K extends keyof ComposerOptions>(key: K, value: ComposerOptions[K]) => void; t: (key: string) => string }) { const disabled = !capability?.compatible; return <fieldset disabled={disabled}><legend>TikTok</legend><Field label={t('TikTok privacy')}><select value={options.tiktokPrivacy} onChange={e => setOption('tiktokPrivacy', e.target.value)}><option value="">{t('Choose privacy')}</option>{capability?.privacy.map(v => <option value={v} key={v}>{v}</option>)}</select></Field><Choice label={t('Allow comments')} value={options.comments} disabled={capability?.commentsDisabled} onChange={v => setOption('comments', v)} /><Choice label={t('Allow Duet')} value={options.duet} disabled={capability?.duetDisabled} onChange={v => setOption('duet', v)} /><Choice label={t('Allow Stitch')} value={options.stitch} disabled={capability?.stitchDisabled} onChange={v => setOption('stitch', v)} /><label><input type="checkbox" checked={options.explicitConsent} onChange={e => setOption('explicitConsent', e.target.checked)} />{t('I have explicit publishing consent')}</label><label><input type="checkbox" checked={options.musicUsageConfirmed} onChange={e => setOption('musicUsageConfirmed', e.target.checked)} />{t('Music usage confirmed')}</label><label><input type="checkbox" checked={options.brandContent} onChange={e => setOption('brandContent', e.target.checked)} />{t('Brand content')}</label><label><input type="checkbox" checked={options.brandOrganic} onChange={e => setOption('brandOrganic', e.target.checked)} />{t('Brand organic')}</label></fieldset> }
function Choice({ label, value, disabled, onChange }: { label: string; value: boolean | null; disabled?: boolean; onChange: (value: boolean) => void }) { return <fieldset disabled={disabled}><legend>{label}</legend><label><input type="radio" checked={value === true} onChange={() => onChange(true)} />Yes</label><label><input type="radio" checked={value === false} onChange={() => onChange(false)} />No</label></fieldset> }
function Preflight({ result, pending, t }: { result?: Awaited<ReturnType<typeof api.composerPreflight>>; pending: boolean; t: (key: string) => string }) { if (pending) return <p>{t('Проверяем совместимость площадок.')}</p>; if (!result) return null; return <div className={styles.warnings} aria-live="polite">{result.targets.map(target => <div key={target.accountId}>{target.preflight.warnings.map(x => <p key={x}>{label[target.platform]}: {x}</p>)}{target.preflight.requiredFields.length ? <p>{t('Required fields')}: {target.preflight.requiredFields.join(', ')}</p> : null}{target.preflight.reconnectAction ? <p>{t('Reconnect required')}</p> : null}</div>)}</div> }
